#!/usr/bin/env python3
"""Regenerate every generated file in this library from papers.yaml.

papers.yaml is the single source of truth. This script rewrites:

    README.md, README.ko.md
    MANIFEST.md
    topics/*/README.md, topics/*/README.ko.md
    docs/lineage.md, docs/lineage.ko.md
    docs/lab-mapping.md

Files under topics/*/notes/ are hand-written and are never touched here.
docs/reading-paths*.md and docs/links-only.md are hand-written as well.

Every file this script writes begins with a generated-by marker. As a safety
measure the script refuses to overwrite an existing file that does not carry
that marker, so a hand-written file can never be silently replaced by a
generated one.

Verification facts come from two places. SHA256 and byte size are recomputed
here from the files on disk, so they are never stale. The metadata match and
the verified-at timestamp are read from .verify-cache.json, which
scripts/verify.py writes, because they require network calls.

Usage:
    python scripts/build_index.py
    python scripts/build_index.py --check    (report what would change, write nothing)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError as exc:  # pragma: no cover - environment dependent
    print("Missing dependency: pyyaml", file=sys.stderr)
    print("Install it with: pip install pyyaml", file=sys.stderr)
    raise SystemExit(2) from exc

sys.path.insert(0, str(Path(__file__).resolve().parent))
from verify import (  # noqa: E402
    CACHE_PATH,
    PAPERS_YAML,
    ROOT,
    load_cache,
    load_papers,
    pdf_path_for,
    sha256_of,
)

GENERATED_HEADER = (
    "<!-- GENERATED by scripts/build_index.py. Do not edit by hand. "
    "Edit papers.yaml and rerun. -->"
)

TOPIC_ORDER = [
    "01-reasoning",
    "02-acting-and-tools",
    "03-self-correction",
    "04-memory-and-retrieval",
    "05-multi-agent",
    "06-environment-and-interface",
    "07-evaluation",
]

TOPICS: dict[str, dict] = {
    "01-reasoning": {
        "name_en": "Reasoning",
        "name_ko": "Reasoning",
        "line_en": "How a single call is made to produce, sample, and search over intermediate steps.",
        "line_ko": "하나의 호출이 중간 단계를 만들어 내고 sampling하고 탐색하도록 하는 방법.",
        "why_en": (
            "Everything an agent does begins as a single call that produces "
            "intermediate steps. This topic covers how those steps are elicited, "
            "how sampling several of them changes the picture, and what happens "
            "when the steps are searched rather than written straight through. "
            "The other six topics assume this one."
        ),
        "why_ko": (
            "agent가 하는 모든 일은 중간 단계를 만들어 내는 하나의 호출에서 "
            "시작합니다. 이 topic은 그 단계들을 어떻게 이끌어 내는지, 여러 개를 "
            "sampling하면 무엇이 달라지는지, 그리고 단계를 한 줄로 쓰는 대신 "
            "탐색할 때 무슨 일이 생기는지를 다룹니다. 나머지 여섯 topic은 이 "
            "topic을 전제로 합니다."
        ),
        "prereq": [],
    },
    "02-acting-and-tools": {
        "name_en": "Acting and tools",
        "name_ko": "Acting and tools",
        "line_en": "The loop that interleaves reasoning with tool calls, and where tool use comes from.",
        "line_ko": "reasoning과 tool call을 번갈아 수행하는 루프, 그리고 tool use 능력이 어디서 오는가.",
        "why_en": (
            "An agent is a model that can act. This topic is about the loop that "
            "interleaves a reasoning step with a tool call and feeds the result "
            "back, which is the structure underneath every agent in this library. "
            "It also covers the separate question of where tool-calling ability "
            "comes from, as distinct from how a tool interface is designed."
        ),
        "why_ko": (
            "agent는 행동할 수 있는 모델입니다. 이 topic은 reasoning 단계와 tool "
            "call을 번갈아 수행하고 그 결과를 다시 넣는 루프를 다루며, 이 "
            "라이브러리의 모든 agent가 그 구조 위에 있습니다. 또한 tool "
            "interface를 어떻게 설계하는가와는 구분되는 질문, 즉 tool 호출 능력이 "
            "어디서 오는가도 함께 다룹니다."
        ),
        "prereq": ["01-reasoning"],
    },
    "03-self-correction": {
        "name_en": "Self-correction",
        "name_ko": "Self-correction",
        "line_en": "Treating a first attempt as a draft, and critiquing it under an explicit budget.",
        "line_ko": "첫 시도를 초안으로 다루고, 명시적 예산 아래에서 그것을 비평하기.",
        "why_en": (
            "A first attempt is a draft. This topic covers the shapes that let a "
            "system read its own output, say what is wrong with it, and try again. "
            "The two papers here are contemporaneous and take different positions "
            "on where the critique should live, which is why they are worth "
            "reading next to each other."
        ),
        "why_ko": (
            "첫 시도는 초안입니다. 이 topic은 시스템이 자기 출력을 읽고 무엇이 "
            "잘못됐는지 말한 뒤 다시 시도하게 하는 형태들을 다룹니다. 여기의 두 "
            "논문은 동시기에 나왔고 비평이 어디에 있어야 하는가에 대해 다른 입장을 "
            "취하므로 나란히 읽을 가치가 있습니다."
        ),
        "prereq": ["02-acting-and-tools"],
    },
    "04-memory-and-retrieval": {
        "name_en": "Memory and retrieval",
        "name_ko": "Memory and retrieval",
        "line_en": "Bringing outside facts into a finite context window, and managing what stays there.",
        "line_ko": "유한한 context window로 외부 사실을 가져오고, 그 안에 무엇을 남길지 관리하기.",
        "why_en": (
            "A context window is finite and a model's weights are fixed at "
            "training time. This topic covers bringing outside facts in at request "
            "time, and then the follow-on problem of deciding what stays in the "
            "window once there is more material than room."
        ),
        "why_ko": (
            "context window는 유한하고 모델의 weight는 학습 시점에 고정됩니다. 이 "
            "topic은 요청 시점에 외부 사실을 가져오는 방법과, 자리보다 자료가 많아진 "
            "뒤에 무엇을 window에 남길지 결정하는 후속 문제를 다룹니다."
        ),
        "prereq": [],
    },
    "05-multi-agent": {
        "name_en": "Multi-agent",
        "name_ko": "Multi-agent",
        "line_en": "Several agents, or one agent playing several roles, and the coordination that requires.",
        "line_ko": "여러 agent, 또는 여러 역할을 맡은 하나의agent, 그리고 그에 필요한 조정.",
        "why_en": (
            "Several agents, or one agent playing several roles. This topic sits "
            "late in the default reading path on purpose: the coordination "
            "questions only become legible once the single-agent loop and its "
            "failure modes are familiar."
        ),
        "why_ko": (
            "여러 agent, 또는 여러 역할을 맡은 하나의 agent를 다룹니다. 이 topic이 "
            "기본 읽기 경로에서 뒤에 오는 것은 의도된 배치입니다. 조정에 관한 "
            "질문들은 단일 agent 루프와 그 실패 양상에 익숙해진 뒤에야 제대로 "
            "읽히기 때문입니다."
        ),
        "prereq": ["02-acting-and-tools", "03-self-correction"],
    },
    "06-environment-and-interface": {
        "name_en": "Environment and interface",
        "name_ko": "Environment and interface",
        "line_en": "The action surface an agent is given, treated as a design variable rather than a given.",
        "line_ko": "agent에게 주어지는 행동 표면을 주어진 조건이 아니라 설계 변수로 다루기.",
        "why_en": (
            "What an agent can do is bounded by the interface it is handed. This "
            "topic treats the environment and the action surface as things you "
            "design rather than as fixed context, which is the same argument the "
            "lab makes about tool descriptions and schemas."
        ),
        "why_ko": (
            "agent가 할 수 있는 일은 그에게 주어진 interface에 의해 제한됩니다. 이 "
            "topic은 환경과 행동 표면을 고정된 조건이 아니라 설계 대상으로 다루며, "
            "이는 lab이 tool description과 schema에 대해 펴는 논지와 같습니다."
        ),
        "prereq": ["02-acting-and-tools"],
    },
    "07-evaluation": {
        "name_en": "Evaluation",
        "name_ko": "Evaluation",
        "line_en": "What agent benchmarks actually measure, and what they leave out.",
        "line_ko": "agent benchmark가 실제로 무엇을 측정하고 무엇을 빠뜨리는가.",
        "why_en": (
            "Without an evaluation, a change to an agent is a guess. This topic "
            "covers how these benchmarks are constructed, what that construction "
            "makes measurable, and what it necessarily leaves out. Read it before "
            "the multi-agent papers, so that claims about coordination have "
            "somewhere to land."
        ),
        "why_ko": (
            "evaluation이 없으면 agent에 대한 변경은 추측입니다. 이 topic은 이 "
            "benchmark들이 어떻게 구성되는지, 그 구성이 무엇을 측정 가능하게 "
            "만드는지, 그리고 필연적으로 무엇을 빠뜨리는지를 다룹니다. 조정에 관한 "
            "주장을 검증할 자리를 만들기 위해 multi-agent 논문보다 먼저 읽으세요."
        ),
        "prereq": ["02-acting-and-tools"],
    },
}

# One-line study framing per paper. These are reading prompts, not claims about
# what any paper reports. Nothing here states a result, a score, or a size.
TAKEAWAYS: dict[str, dict[str, str]] = {
    "2201.11903": {
        "en": "Read this for the move that makes intermediate steps part of the output rather than something the model does silently.",
        "ko": "중간 단계를 모델이 조용히 처리하는 것이 아니라 출력의 일부로 만드는 전환을 보기 위해 읽습니다.",
    },
    "2203.11171": {
        "en": "Read this as the sampling-and-aggregation view of a reasoning call, and compare it with the voting variant built in the lab.",
        "ko": "reasoning 호출을 sampling과 집계의 관점으로 보는 시각으로 읽고, lab에서 만드는 voting 변형과 비교하세요.",
    },
    "2305.10601": {
        "en": "Read this for what changes when reasoning is treated as a search over branches rather than as a single line.",
        "ko": "reasoning을 한 줄이 아니라 분기에 대한 탐색으로 다룰 때 무엇이 달라지는지 보기 위해 읽습니다.",
    },
    "2210.03629": {
        "en": "Read this as the direct ancestor of the agent loop: reasoning and acting placed in one alternating cycle.",
        "ko": "reasoning과 acting을 하나의 교대 주기에 놓은, agent 루프의 직접적인 조상으로 읽습니다.",
    },
    "2302.04761": {
        "en": "Read this for the question of where tool-calling ability comes from, as distinct from how a tool interface is designed.",
        "ko": "tool interface를 어떻게 설계하는가와 구분되는 질문, 즉 tool 호출 능력이 어디서 오는가를 보기 위해 읽습니다.",
    },
    "2303.11366": {
        "en": "Read this for the idea of carrying a critique forward between attempts instead of simply resampling.",
        "ko": "단순히 재sampling하는 대신 시도 사이로 비평을 이어 나른다는 발상을 보기 위해 읽습니다.",
    },
    "2303.17651": {
        "en": "Read this next to Reflexion as the contemporaneous take that keeps the critique inside a single model.",
        "ko": "비평을 하나의 모델 안에 두는 동시기의 접근으로, Reflexion과 나란히 읽습니다.",
    },
    "2005.11401": {
        "en": "Read this for the original framing of retrieval as a component of generation rather than a preprocessing step.",
        "ko": "retrieval을 전처리 단계가 아니라 generation의 구성 요소로 보는 최초의 규정을 보기 위해 읽습니다.",
    },
    "2310.08560": {
        "en": "Read this for the analogy between managing a context window and managing virtual memory.",
        "ko": "context window 관리와 virtual memory 관리 사이의 유비를 보기 위해 읽습니다.",
    },
    "2304.03442": {
        "en": "Read this for its memory architecture, which is the part that transfers to systems that are not simulations.",
        "ko": "시뮬레이션이 아닌 시스템으로도 옮겨 가는 부분인 memory architecture를 보기 위해 읽습니다.",
    },
    "2308.08155": {
        "en": "Read this as a framework-shaped answer to multi-agent conversation, and compare its abstractions with an orchestrator written by hand.",
        "ko": "multi-agent 대화에 대한 framework 형태의 답으로 읽고, 그 추상화를 직접 작성한 orchestrator와 비교하세요.",
    },
    "2305.16291": {
        "en": "Read this for the idea of an agent accumulating reusable skills inside an open-ended environment.",
        "ko": "열린 환경 안에서 agent가 재사용 가능한 skill을 축적한다는 발상을 보기 위해 읽습니다.",
    },
    "2405.15793": {
        "en": "Read this for the agent-computer interface argument: the interface an agent is handed is itself a design variable.",
        "ko": "agent-computer interface에 대한 논지, 즉 agent에게 주어지는 interface 자체가 설계 변수라는 주장을 보기 위해 읽습니다.",
    },
    "2310.06770": {
        "en": "Read this for how a benchmark can be constructed out of real repository history, and what that construction makes measurable.",
        "ko": "실제 저장소 이력으로 benchmark를 구성하는 방법과, 그 구성이 무엇을 측정 가능하게 만드는지 보기 위해 읽습니다.",
    },
    "2307.13854": {
        "en": "Read this for what an environment has to provide before an agent evaluation carried out in it means anything.",
        "ko": "그 안에서 수행되는 agent evaluation이 의미를 갖기 위해 환경이 무엇을 제공해야 하는지 보기 위해 읽습니다.",
    },
    "2406.12045": {
        "en": "Read this for the tool-agent-user triangle, and for how a benchmark handles a user who is part of the loop.",
        "ko": "tool, agent, user의 삼각 구도와, 루프의 일부인 사용자를 benchmark가 어떻게 다루는지 보기 위해 읽습니다.",
    },
}

# Optional per-topic closing section. Keyed by topic, rendered after the paper
# list. This is the one place in a topic README that is an argument rather than
# an index, so it is kept as literal prose rather than assembled from fields.
DECISION_FRAMES: dict[str, dict[str, str]] = {
    "01-reasoning": {
        "en": """The papers are variations on three decisions, not three
techniques to memorize. What is worth carrying is the decision, because a
paper published next year will be another setting of the same three.

| Approach | What it requires | Budget |
| --- | --- | --- |
| One pass with intermediate steps ([2201.11903](https://arxiv.org/abs/2201.11903)) | Nothing beyond room to emit the steps | Roughly one call |
| Parallel samples plus aggregation ([2203.11171](https://arxiv.org/abs/2203.11171)) | Answers that can be compared for equality | N times |
| Search over branches ([2305.10601](https://arxiv.org/abs/2305.10601)) | A state evaluator good enough to prune on | Many times over |

Three questions decide the row, and they are the thing to ask when a new
task arrives.

1. **Can the answer be checked automatically?** If yes, parallel sampling
   with a verifier is hard to beat. If no, the entire width-expanding
   family drops out, because there is nothing to aggregate over and
   nothing to prune on.
2. **Do failures come from the plan or from the execution?** Execution
   failures want tools and grounding, which is `02-acting-and-tools`.
   Planning failures are the ones worth spending a search structure on.
3. **What cost multiple is allowed?** One, several, or many over is
   usually what actually decides which row above is available, regardless
   of which one would perform best.

Placing a new paper is then a matter of finding its cell rather than
reading it from the beginning.""",
        "ko": """이 논문들은 외워야 할 세 가지 기법이 아니라 세 가지 결정의
변주입니다. 가지고 다닐 가치가 있는 것은 결정 쪽입니다. 내년에 나올 논문도
같은 세 가지를 다르게 잡은 것일 테니까요.

| 접근 | 무엇을 요구하는가 | 예산 |
| --- | --- | --- |
| 중간 단계를 포함한 한 번의 pass ([2201.11903](https://arxiv.org/abs/2201.11903)) | 단계를 내놓을 여유 외에는 없음 | 대략 한 번의 호출 |
| 병렬 sampling과 집계 ([2203.11171](https://arxiv.org/abs/2203.11171)) | 동등성을 비교할 수 있는 답 | N배 |
| 분기에 대한 탐색 ([2305.10601](https://arxiv.org/abs/2305.10601)) | 가지치기를 맡길 만한 state evaluator | 수십 배 |

어느 행을 쓸지는 세 질문이 결정하며, 새 task를 만났을 때 던질 질문이
그것입니다.

1. **답을 자동으로 검증할 수 있는가.** 가능하면 병렬 sampling과 verifier의
   조합을 이기기 어렵습니다. 불가능하면 너비를 넓히는 계열 전체가
   탈락합니다. 집계할 대상도, 가지칠 근거도 없기 때문입니다.
2. **실패가 계획에서 나는가, 실행에서 나는가.** 실행 실패는 tool과 근거를
   원하며 그것은 `02-acting-and-tools`입니다. 탐색 구조를 들일 가치가 있는
   것은 계획 실패 쪽입니다.
3. **예산 몇 배까지 허용되는가.** 한 배인지, 몇 배인지, 수십 배인지가 어느
   행이 성능상 가장 좋은지와 무관하게 어느 행을 쓸 수 있는지를 사실상
   결정합니다.

그러면 새 논문을 놓는 일은 처음부터 읽는 일이 아니라 그것이 들어갈 칸을
찾는 일이 됩니다.""",
    },
}

TIER_NOTE_EN = {
    "core": "core, read first",
    "deep": "deep, read after the core paper in its topic",
    "reference": "reference, consult as needed",
}
TIER_NOTE_KO = {
    "core": "core, 먼저 읽기",
    "deep": "deep, 해당 topic의 core 논문 다음에 읽기",
    "reference": "reference, 필요할 때 참고",
}

DEFAULT_PATH = ["01-reasoning", "02-acting-and-tools", "03-self-correction",
                "04-memory-and-retrieval", "07-evaluation", "05-multi-agent",
                "06-environment-and-interface"]

EDITORIAL_NOTE_EN = (
    "The `builds_on`, `extended_by`, and `related` edges in this library are "
    "**editorial groupings chosen for study purposes**. They are not a claim "
    "about formal citation lineage, and no citation graph was consulted to "
    "produce them."
)
EDITORIAL_NOTE_KO = (
    "이 라이브러리의 `builds_on`, `extended_by`, `related` 간선은 **학습 목적으로 "
    "선택한 편집상의 묶음**입니다. 형식적인 인용 계보에 대한 주장이 아니며, 이를 "
    "만들기 위해 citation graph를 참조하지 않았습니다."
)


def arxiv_abs(arxiv_id: str) -> str:
    return f"https://arxiv.org/abs/{arxiv_id}"


def write_generated(path: Path, content: str, *, check: bool, report: list) -> None:
    """Write a generated file, refusing to clobber a hand-written one."""
    relative = path.relative_to(ROOT)
    if path.is_file():
        existing = path.read_text(encoding="utf-8")
        if not existing.startswith(GENERATED_HEADER):
            report.append(("REFUSED", str(relative), "exists without a generated marker"))
            return
        if existing == content:
            report.append(("unchanged", str(relative), ""))
            return
        action = "would update" if check else "updated"
    else:
        action = "would create" if check else "created"
    if not check:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    report.append((action, str(relative), ""))


def paper_link(entry: dict, from_dir: Path) -> str:
    """A markdown link to the PDF of a paper, relative to from_dir."""
    target = pdf_path_for(entry)
    try:
        rel = Path(*([".."] * len(from_dir.relative_to(ROOT).parts))) / target.relative_to(ROOT)
    except ValueError:
        rel = target
    return str(rel)


def render_readme(papers: list[dict], lang: str) -> str:
    en = lang == "en"
    lines = [GENERATED_HEADER, ""]
    if en:
        lines += [
            "# Agent systems paper library",
            "",
            "A small, deliberately bounded reading library for studying agent",
            "systems. Sixteen papers, seven topics, one PDF per paper stored in",
            "exactly one place.",
            "",
            "`papers.yaml` is the only file a human edits. Everything else that",
            "carries a generated marker, including this README, is produced by",
            "`scripts/build_index.py`. Notes under `topics/*/notes/` are",
            "hand-written and are never regenerated.",
            "",
            "## What is and is not here",
            "",
            "Each paper is downloaded from arXiv, checked against the arXiv API,",
            "and recorded in `MANIFEST.md` with a SHA256 and the outcome of every",
            "check. Author lists and years come from the arXiv API rather than",
            "being typed by hand.",
            "",
            "There are no benchmark scores, accuracy numbers, parameter counts, or",
            "dataset sizes anywhere in this library. Nothing is summarized on your",
            "behalf: the note stubs are empty by design, and the one-line entries",
            "in each topic README are reading prompts rather than descriptions of",
            "results. If you want to know what a paper found, read the paper.",
            "",
            "## The seven topics",
            "",
        ]
        for topic in TOPIC_ORDER:
            info = TOPICS[topic]
            lines.append(
                f"- [`{topic}`](topics/{topic}/README.md) **{info['name_en']}**. "
                f"{info['line_en']}"
            )
        lines += [
            "",
            "## Papers",
            "",
            "| Topic | arXiv id | Title | Tier |",
            "| --- | --- | --- | --- |",
        ]
    else:
        lines += [
            "# Agent systems paper library",
            "",
            "agent system을 공부하기 위한, 의도적으로 범위를 좁힌 소규모 reading",
            "library입니다. 논문 열여섯 편, topic 일곱 개이며, 논문 하나의 PDF는",
            "정확히 한 곳에만 저장됩니다.",
            "",
            "사람이 직접 편집하는 파일은 `papers.yaml` 하나뿐입니다. generated",
            "marker가 붙은 나머지 파일은 이 README를 포함해 모두",
            "`scripts/build_index.py`가 생성합니다. `topics/*/notes/` 아래의 note는",
            "손으로 작성하며 절대 다시 생성되지 않습니다.",
            "",
            "## 여기에 있는 것과 없는 것",
            "",
            "각 논문은 arXiv에서 내려받아 arXiv API와 대조 검증하고, SHA256과 모든",
            "check 결과를 `MANIFEST.md`에 기록합니다. author 목록과 연도는 손으로",
            "입력하지 않고 arXiv API에서 가져옵니다.",
            "",
            "이 라이브러리 어디에도 benchmark 점수, 정확도 수치, parameter 수,",
            "dataset 크기는 없습니다. 무엇도 대신 요약해 주지 않습니다. note stub은",
            "의도적으로 비어 있고, 각 topic README의 한 줄 항목은 결과에 대한 설명이",
            "아니라 읽기 위한 실마리입니다. 논문이 무엇을 밝혀냈는지 알고 싶다면",
            "논문을 읽으세요.",
            "",
            "## 일곱 개의 topic",
            "",
        ]
        for topic in TOPIC_ORDER:
            info = TOPICS[topic]
            lines.append(
                f"- [`{topic}`](topics/{topic}/README.ko.md) **{info['name_ko']}**. "
                f"{info['line_ko']}"
            )
        lines += [
            "",
            "## 논문 목록",
            "",
            "| Topic | arXiv id | 제목 | Tier |",
            "| --- | --- | --- | --- |",
        ]

    for topic in TOPIC_ORDER:
        for entry in papers:
            if entry["primary_topic"] != topic:
                continue
            lines.append(
                f"| `{topic}` | [{entry['arxiv_id']}]({arxiv_abs(entry['arxiv_id'])}) "
                f"| {entry['title']} | {entry['tier']} |"
            )

    if en:
        lines += [
            "",
            "## Default reading path",
            "",
            " -> ".join(f"`{t}`" for t in DEFAULT_PATH),
            "",
            "Multi-agent comes late on purpose: the single-agent loop should be",
            "understood before coordination between agents is worth reading about.",
            "Two other routes, and the caveat that all three are a study opinion",
            "rather than a consensus, are in",
            "[`docs/reading-paths.md`](docs/reading-paths.md).",
            "",
            "## Adding a paper",
            "",
            "```bash",
            "python scripts/add_paper.py 2402.01030 \\",
            "    --topic 02-acting-and-tools \\",
            "    --tier deep \\",
            "    --builds-on 2210.03629 \\",
            "    --lab-refs 07-tool-design-aci",
            "```",
            "",
            "The script refuses ids already in `papers.yaml`, fetches title,",
            "authors, and year from the arXiv API, downloads the PDF into the",
            "topic folder, verifies it, appends the entry, creates the two note",
            "stubs if they are absent, and reruns this index. A download that",
            "fails verification is deleted rather than kept.",
            "",
            "## Checking what is on disk",
            "",
            "```bash",
            "python scripts/verify.py --all        # re-verify every paper",
            "python scripts/verify.py --all --offline   # skip the arXiv API",
            "python scripts/build_index.py         # regenerate the generated files",
            "```",
            "",
            "## Related reading that is not mirrored here",
            "",
            "See [`docs/links-only.md`](docs/links-only.md).",
        ]
    else:
        lines += [
            "",
            "## 기본 읽기 경로",
            "",
            " -> ".join(f"`{t}`" for t in DEFAULT_PATH),
            "",
            "multi-agent가 뒤에 오는 것은 의도된 배치입니다. agent 사이의 조정을",
            "읽을 가치가 생기려면 먼저 단일 agent 루프를 이해해야 하기 때문입니다.",
            "다른 두 경로와, 세 경로 모두가 합의가 아니라 학습상의 견해라는 단서는",
            "[`docs/reading-paths.ko.md`](docs/reading-paths.ko.md)에 있습니다.",
            "",
            "## 논문 추가하기",
            "",
            "```bash",
            "python scripts/add_paper.py 2402.01030 \\",
            "    --topic 02-acting-and-tools \\",
            "    --tier deep \\",
            "    --builds-on 2210.03629 \\",
            "    --lab-refs 07-tool-design-aci",
            "```",
            "",
            "이 script는 `papers.yaml`에 이미 있는 id를 거부하고, arXiv API에서",
            "제목과 author와 연도를 가져오고, PDF를 topic 폴더로 내려받고, 검증하고,",
            "항목을 추가하고, note stub이 없으면 만들고, 이 index를 다시 생성합니다.",
            "검증에 실패한 다운로드는 보관하지 않고 삭제합니다.",
            "",
            "## 디스크 상태 확인",
            "",
            "```bash",
            "python scripts/verify.py --all        # 모든 논문 재검증",
            "python scripts/verify.py --all --offline   # arXiv API 생략",
            "python scripts/build_index.py         # generated 파일 재생성",
            "```",
            "",
            "## 여기에 미러링하지 않은 관련 읽을거리",
            "",
            "[`docs/links-only.md`](docs/links-only.md)를 참고하세요.",
        ]
    return "\n".join(lines) + "\n"


def render_manifest(papers: list[dict], cache: dict) -> str:
    lines = [
        GENERATED_HEADER,
        "",
        "# Manifest",
        "",
        "One row per paper. `sha256` and `bytes` are recomputed from disk every",
        "time this file is generated. `title match` is the page 1 content check",
        "and `metadata match` is the comparison against the arXiv API title; both",
        "come from the last run of `scripts/verify.py`, whose results are cached",
        "in `.verify-cache.json`.",
        "",
        "A dash means the fact is not available because the paper has not been",
        "verified since it was last downloaded.",
        "",
        "| File | arXiv id | SHA256 | Bytes | Title match | Metadata match | Verified at |",
        "| --- | --- | --- | ---: | --- | --- | --- |",
    ]
    failures: list[tuple[str, list[str]]] = []
    missing: list[str] = []
    for entry in papers:
        path = pdf_path_for(entry)
        record = cache.get(entry["arxiv_id"], {})
        if path.is_file():
            digest = sha256_of(path)
            size = path.stat().st_size
            filename = str(path.relative_to(ROOT))
        else:
            digest, size, filename = "", 0, f"(missing) {entry['arxiv_id']}-{entry['slug']}.pdf"
            missing.append(entry["arxiv_id"])

        def mark(value) -> str:
            if value is True:
                return "yes"
            if value is False:
                return "NO"
            return "-"

        lines.append(
            f"| `{filename}` | {entry['arxiv_id']} | `{digest or '-'}` | "
            f"{size if size else '-'} | {mark(record.get('content_ok'))} | "
            f"{mark(record.get('metadata_ok'))} | {record.get('verified_at') or '-'} |"
        )
        if record.get("status") == "FAIL":
            failures.append((entry["arxiv_id"], record.get("reasons", [])))

    lines += ["", "## Summary", ""]
    lines.append(f"- papers recorded: {len(papers)}")
    lines.append(f"- PDFs present on disk: {len(papers) - len(missing)}")
    lines.append(f"- rows marked FAIL by the last verify run: {len(failures)}")
    if failures:
        lines += ["", "### Failures", ""]
        for arxiv_id, reasons in failures:
            lines.append(f"- **{arxiv_id}**")
            for reason in reasons:
                lines.append(f"  - {reason}")
    else:
        lines += ["", "No paper is currently marked FAIL."]
    return "\n".join(lines) + "\n"


def render_topic_readme(topic: str, papers: list[dict], lang: str) -> str:
    en = lang == "en"
    info = TOPICS[topic]
    own = [p for p in papers if p["primary_topic"] == topic]
    cross = [p for p in papers if topic in (p.get("also_relevant_to") or [])]
    suffix = "README.md" if en else "README.ko.md"

    lines = [GENERATED_HEADER, ""]
    lines.append(f"# {topic} - {info['name_en'] if en else info['name_ko']}")
    lines.append("")
    lines.append("## Why this topic exists" if en else "## 이 topic이 존재하는 이유")
    lines.append("")
    lines.append(info["why_en"] if en else info["why_ko"])
    lines.append("")
    lines.append("## Prerequisite topics" if en else "## 선행 topic")
    lines.append("")
    if info["prereq"]:
        for prereq in info["prereq"]:
            name = TOPICS[prereq]["name_en" if en else "name_ko"]
            lines.append(f"- [`{prereq}`](../{prereq}/{suffix}) {name}")
    else:
        lines.append(
            "None. This topic is an entry point."
            if en
            else "없습니다. 이 topic은 시작 지점입니다."
        )
    lines.append("")
    lines.append("## Papers in this topic" if en else "## 이 topic의 논문")
    lines.append("")
    if not own:
        lines.append("None yet." if en else "아직 없습니다.")
    for entry in own:
        tier = (TIER_NOTE_EN if en else TIER_NOTE_KO)[entry["tier"]]
        takeaway = TAKEAWAYS.get(entry["arxiv_id"], {}).get("en" if en else "ko", "")
        pdf_name = f"{entry['arxiv_id']}-{entry['slug']}.pdf"
        note_name = f"{entry['arxiv_id']}-{entry['slug']}" + (".md" if en else ".ko.md")
        lines.append(f"### {entry['title']}")
        lines.append("")
        authors = entry.get("authors") or []
        if authors:
            shown = ", ".join(authors[:3])
            if len(authors) > 3:
                shown += (" and others" if en else " 외")
            year = entry.get("year") or ""
            lines.append(f"{shown}{f' ({year})' if year else ''}")
            lines.append("")
        lines.append(
            f"- arXiv: [{entry['arxiv_id']}]({arxiv_abs(entry['arxiv_id'])})"
        )
        lines.append(f"- PDF: [`{pdf_name}`](pdf/{pdf_name})")
        lines.append(f"- Notes: [`{note_name}`](notes/{note_name})")
        lines.append(f"- Tier: {tier}")
        if takeaway:
            lines.append("")
            lines.append(takeaway)
        lines.append("")
    lines.append(
        "## Papers filed elsewhere that also apply here"
        if en
        else "## 다른 곳에 보관되어 있지만 여기에도 해당하는 논문"
    )
    lines.append("")
    if cross:
        lines.append(
            "These are stored under their own primary topic. The PDF lives in "
            "exactly one place and is linked, never copied."
            if en
            else "이 논문들은 각자의 primary topic 아래에 보관되어 있습니다. PDF는 "
            "정확히 한 곳에만 존재하며 복사하지 않고 링크만 겁니다."
        )
        lines.append("")
        for entry in cross:
            home = entry["primary_topic"]
            pdf_name = f"{entry['arxiv_id']}-{entry['slug']}.pdf"
            lines.append(
                f"- {entry['title']} "
                f"([{entry['arxiv_id']}]({arxiv_abs(entry['arxiv_id'])}), "
                f"filed under [`{home}`](../{home}/{suffix}), "
                f"[PDF](../{home}/pdf/{pdf_name}))"
                if en
                else f"- {entry['title']} "
                f"([{entry['arxiv_id']}]({arxiv_abs(entry['arxiv_id'])}), "
                f"[`{home}`](../{home}/{suffix})에 보관, "
                f"[PDF](../{home}/pdf/{pdf_name}))"
            )
    else:
        lines.append(
            "None." if en else "없습니다."
        )
    lines.append("")

    frame = DECISION_FRAMES.get(topic)
    if frame:
        lines.append(
            "## What to carry instead of the papers"
            if en
            else "## 논문 대신 가지고 다닐 것"
        )
        lines.append("")
        lines.append(frame["en" if en else "ko"])
        lines.append("")

    return "\n".join(lines) + "\n"


def render_lineage(papers: list[dict], lang: str) -> str:
    en = lang == "en"
    by_id = {p["arxiv_id"]: p for p in papers}
    order = [p["arxiv_id"] for p in papers]

    def label(arxiv_id: str) -> str:
        entry = by_id.get(arxiv_id)
        if entry is None:
            return f"{arxiv_id} (not in this library)"
        return f"{arxiv_id}  {entry['slug']}  [{entry['primary_topic']}]"

    children: dict[str, list[str]] = {pid: [] for pid in order}
    for entry in papers:
        for child in entry.get("extended_by") or []:
            if child in children[entry["arxiv_id"]]:
                continue
            children[entry["arxiv_id"]].append(child)

    roots = [
        pid for pid in order if not (by_id[pid].get("builds_on") or [])
    ]

    drawn: set[str] = set()
    tree_lines: list[str] = []

    def walk(node: str, prefix: str, is_last: bool, depth: int) -> None:
        connector = "" if depth == 0 else ("\\-- " if is_last else "+-- ")
        # A paper reached by more than one edge is shown at each position so the
        # graph stays faithful to the recorded edges, but it is only expanded
        # once and every later appearance says so.
        repeated = node in drawn
        suffix = "   (also shown above)" if repeated else ""
        tree_lines.append(f"{prefix}{connector}{label(node)}{suffix}")
        drawn.add(node)
        if repeated:
            return
        kids = [k for k in children.get(node, []) if k in by_id]
        if depth == 0:
            child_prefix = ""
        else:
            child_prefix = prefix + ("    " if is_last else "|   ")
        for index, kid in enumerate(kids):
            walk(kid, child_prefix, index == len(kids) - 1, depth + 1)

    for root in roots:
        walk(root, "", True, 0)
        tree_lines.append("")
    while tree_lines and not tree_lines[-1]:
        tree_lines.pop()

    related_pairs: list[tuple[str, str]] = []
    for entry in papers:
        for other in entry.get("related") or []:
            pair = tuple(sorted((entry["arxiv_id"], other)))
            if pair not in related_pairs:
                related_pairs.append(pair)

    lines = [GENERATED_HEADER, ""]
    if en:
        lines += [
            "# Lineage",
            "",
            EDITORIAL_NOTE_EN,
            "",
            "The tree below is drawn from `builds_on` and `extended_by`. A paper",
            "that extends two others appears under both; the second appearance is",
            "marked rather than expanded twice.",
            "",
            "## Reading order graph",
            "",
            "```text",
        ]
    else:
        lines += [
            "# Lineage",
            "",
            EDITORIAL_NOTE_KO,
            "",
            "아래 트리는 `builds_on`과 `extended_by`로부터 그린 것입니다. 두 논문을",
            "확장하는 논문은 양쪽 모두에 나타나며, 두 번째 등장은 다시 펼치지 않고",
            "표시만 합니다.",
            "",
            "## 읽기 순서 그래프",
            "",
            "```text",
        ]
    lines += tree_lines
    lines += ["```", ""]
    lines.append("## Contemporaneous work" if en else "## 동시기 연구")
    lines.append("")
    lines.append(
        "These pairs are grouped as `related`: work of the same period with no "
        "direction of influence asserted between them."
        if en
        else "다음 쌍은 `related`로 묶여 있습니다. 같은 시기의 연구이며 그들 사이에 "
        "영향의 방향을 주장하지 않습니다."
    )
    lines.append("")
    if related_pairs:
        for left, right in related_pairs:
            lines.append(f"- {label(left)}  <->  {label(right)}")
    else:
        lines.append("None recorded." if en else "기록된 것이 없습니다.")
    lines.append("")
    return "\n".join(lines) + "\n"


def render_lab_mapping(papers: list[dict]) -> str:
    lines = [
        GENERATED_HEADER,
        "",
        "# Paper to lab mapping",
        "",
        "Each paper mapped to the folders in the sibling lab repository whose",
        "subject it bears on. The mapping is an editorial reading aid: it says",
        "where a paper is worth having in mind while working through a lab, not",
        "that a lab implements a paper.",
        "",
        "| arXiv id | Paper | Primary topic | Lab folders |",
        "| --- | --- | --- | --- |",
    ]
    for topic in TOPIC_ORDER:
        for entry in papers:
            if entry["primary_topic"] != topic:
                continue
            labs = ", ".join(f"`{ref}`" for ref in (entry.get("lab_refs") or []))
            lines.append(
                f"| [{entry['arxiv_id']}]({arxiv_abs(entry['arxiv_id'])}) "
                f"| {entry['title']} | `{topic}` | {labs or '-'} |"
            )

    by_lab: dict[str, list[dict]] = {}
    for entry in papers:
        for ref in entry.get("lab_refs") or []:
            by_lab.setdefault(ref, []).append(entry)

    lines += ["", "## By lab", "", "| Lab folder | Papers |", "| --- | --- |"]
    for lab in sorted(by_lab):
        ids = ", ".join(
            f"[{p['arxiv_id']}]({arxiv_abs(p['arxiv_id'])})" for p in by_lab[lab]
        )
        lines.append(f"| `{lab}` | {ids} |")
    lines.append("")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate generated files from papers.yaml.")
    parser.add_argument(
        "--check", action="store_true", help="report what would change, write nothing"
    )
    args = parser.parse_args(argv)

    papers = load_papers()
    cache = load_cache()
    report: list[tuple[str, str, str]] = []

    write_generated(ROOT / "README.md", render_readme(papers, "en"), check=args.check, report=report)
    write_generated(ROOT / "README.ko.md", render_readme(papers, "ko"), check=args.check, report=report)
    write_generated(ROOT / "MANIFEST.md", render_manifest(papers, cache), check=args.check, report=report)
    for topic in TOPIC_ORDER:
        write_generated(
            ROOT / "topics" / topic / "README.md",
            render_topic_readme(topic, papers, "en"),
            check=args.check,
            report=report,
        )
        write_generated(
            ROOT / "topics" / topic / "README.ko.md",
            render_topic_readme(topic, papers, "ko"),
            check=args.check,
            report=report,
        )
    write_generated(ROOT / "docs" / "lineage.md", render_lineage(papers, "en"), check=args.check, report=report)
    write_generated(ROOT / "docs" / "lineage.ko.md", render_lineage(papers, "ko"), check=args.check, report=report)
    write_generated(ROOT / "docs" / "lab-mapping.md", render_lab_mapping(papers), check=args.check, report=report)

    refused = [row for row in report if row[0] == "REFUSED"]
    for action, path, note in report:
        suffix = f"  ({note})" if note else ""
        print(f"{action:<14}{path}{suffix}")
    print(f"\n{len(report)} generated files considered, {len(refused)} refused")
    return 1 if refused else 0


if __name__ == "__main__":
    raise SystemExit(main())
